import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  header: { backgroundColor: '#5DADE2', paddingHorizontal: 24, paddingVertical: 32, paddingTop: 50 },
  headerContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { color: 'white', fontSize: 24, fontWeight: 'bold' },
  notificationContainer: { position: 'relative' },
  notificationDot: { position: 'absolute', top: 0, right: 0, width: 10, height: 10, backgroundColor: '#EF4444', borderRadius: 5 },
  content: { flex: 1 },
  contentContainer: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 20 },
  calculatorCard: { backgroundColor: 'white', borderRadius: 12, padding: 20, marginBottom: 16, borderWidth: 1, borderColor: '#E5E7EB', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  iconCircle: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  greenBg: { backgroundColor: '#D1FAE5' },
  yellowBg: { backgroundColor: '#FEF3C7' },
  blueBg: { backgroundColor: '#DBEAFE' },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#111827' },
  description: { fontSize: 14, color: '#6B7280', marginBottom: 16 },
  calculateButton: { backgroundColor: '#10B981', borderRadius: 8, paddingVertical: 14, alignItems: 'center' },
  calculateButtonText: { color: 'white', fontSize: 16, fontWeight: '600' },
  summaryContainer: { marginTop: 16, padding: 16, backgroundColor: '#F0FDF4', borderRadius: 8 },
  summaryTitle: { fontSize: 14, fontWeight: '600', color: '#166534', marginBottom: 4 },
  summaryText: { fontSize: 14, color: '#166534' },
  rewardsManagementCard: { backgroundColor: 'white', borderRadius: 12, padding: 20, marginBottom: 16, borderWidth: 1, borderColor: '#E5E7EB', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  addRewardButton: { backgroundColor: '#F59E0B', borderRadius: 8, paddingVertical: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 8 },
  addRewardButtonText: { color: 'white', fontSize: 16, fontWeight: '600' },
  rewardTasksList: { marginTop: 20 },
  rewardTasksTitle: { fontSize: 16, fontWeight: '600', color: '#111827', marginBottom: 12 },
  emptyRewardsState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, marginTop: 20 },
  pickupsSection: { marginBottom: 16 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
  emptyStateText: { fontSize: 16, color: '#9CA3AF', marginTop: 12 },
  loader: { marginVertical: 20 },
  bottomPadding: { height: 20 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center' },
  modalScrollContent: { padding: 20 },
  modalContent: { backgroundColor: 'white', borderRadius: 16, padding: 24, width: '100%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#111827' },
  sectionLabel: { fontSize: 16, fontWeight: '600', color: '#111827', marginTop: 16, marginBottom: 12 },
  modalLabel: { fontSize: 14, color: '#6B7280', marginBottom: 8, marginTop: 8 },
  modalInput: { borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 8, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16, backgroundColor: '#F9FAFB' },
  summaryBox: { backgroundColor: '#F0FDF4', borderRadius: 8, padding: 16, marginTop: 16 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  summaryLabel: { fontSize: 14, color: '#166534', fontWeight: '500' },
  summaryValue: { fontSize: 16, color: '#166534', fontWeight: '600' },
  summaryValueLarge: { fontSize: 24, color: '#10B981', fontWeight: 'bold' },
  rewardTypeButtons: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  rewardTypeButton: { flex: 1, paddingVertical: 12, borderRadius: 8, borderWidth: 1, borderColor: '#D1D5DB', backgroundColor: '#F9FAFB', alignItems: 'center' },
  rewardTypeButtonSelected: { backgroundColor: '#F59E0B', borderColor: '#F59E0B' },
  rewardTypeButtonText: { fontSize: 14, color: '#6B7280', fontWeight: '500' },
  rewardTypeButtonTextSelected: { color: 'white' },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  iconButton: { width: '48%', padding: 16, borderRadius: 10, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  iconButtonSelected: { borderColor: '#F59E0B', borderWidth: 2 },
  iconButtonLabel: { fontSize: 12, fontWeight: '600', marginTop: 6 },
  modalButtons: { flexDirection: 'row', gap: 12, marginTop: 24 },
  modalCancelButton: { flex: 1, paddingVertical: 14, borderRadius: 8, borderWidth: 1, borderColor: '#D1D5DB', alignItems: 'center' },
  modalCancelText: { fontSize: 16, color: '#6B7280', fontWeight: '600' },
  modalSaveButton: { flex: 1, paddingVertical: 14, borderRadius: 8, backgroundColor: '#10B981', alignItems: 'center' },
  modalSaveText: { fontSize: 16, color: 'white', fontWeight: '600' },
  statusBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 },
  statusScheduled: { backgroundColor: '#DBEAFE' },
  statusPending: { backgroundColor: '#FEF3C7' },
  statusCompleted: { backgroundColor: '#DCFCE7' },
});