// styles/dashboardStyles.js
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9FAFB' },
  header: { backgroundColor: '#5DADE2', paddingHorizontal: 24, paddingVertical: 32 },
  headerContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { color: 'white', fontSize: 24, fontWeight: 'bold' },
  headerSubtitle: { color: 'rgba(255, 255, 255, 0.9)', fontSize: 14, marginTop: 4 },
  headerIcons: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationContainer: { position: 'relative' },
  notificationDot: { 
    position: 'absolute', 
    top: 0, 
    right: 0, 
    width: 10, 
    height: 10, 
    backgroundColor: '#EF4444', 
    borderRadius: 5, 
    borderWidth: 2, 
    borderColor: '#5DADE2' 
  },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 24 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  card: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    width: '48%',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  iconCircle: { width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
  greenBg: { backgroundColor: '#D1FAE5' },
  purpleBg: { backgroundColor: '#E9D5FF' },
  cardLabel: { color: '#9CA3AF', fontSize: 14, marginBottom: 8 },
  billAmount: { fontSize: 30, fontWeight: 'bold', color: '#111827', marginBottom: 8 },
  billSubtext: { fontSize: 12, color: '#EF4444', marginBottom: 8 },
  loader: { marginVertical: 20 },
  payButton: { backgroundColor: '#10B981', borderRadius: 8, paddingVertical: 12, alignItems: 'center' },
  payButtonText: { color: 'white', fontSize: 16, fontWeight: '600' },
  wasteInfo: { marginBottom: 12 },
  wasteRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  wasteLabel: { fontSize: 12, color: '#6B7280' },
  wasteValue: { fontSize: 12, fontWeight: '600', color: '#111827' },
  wasteTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  wasteTotalLabel: { fontSize: 14, fontWeight: '600', color: '#111827' },
  wasteTotalValue: { fontSize: 16, fontWeight: 'bold', color: '#10B981' },
  noDataText: { fontSize: 14, color: '#9CA3AF', textAlign: 'center', marginVertical: 20 },
  noScheduleText: { fontSize: 14, color: '#9CA3AF', marginBottom: 12 },
  noRewardText: { fontSize: 14, color: '#9CA3AF', marginBottom: 12 },
  viewHistoryButton: { backgroundColor: '#3B82F6', borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
  viewHistoryText: { color: 'white', fontSize: 14, fontWeight: '600' },
  redeemButton: { backgroundColor: '#3B82F6', borderRadius: 8, paddingVertical: 12, alignItems: 'center', marginTop: 8 },
  redeemButtonText: { color: 'white', fontSize: 16, fontWeight: '600' },
  rewardName: { fontSize: 18, fontWeight: '600', color: '#111827', marginBottom: 8 },
  progressContainer: { marginBottom: 12 },
  progressBar: { height: 6, backgroundColor: '#E5E7EB', borderRadius: 3, overflow: 'hidden', marginBottom: 6 },
  progressFill: { height: '100%', backgroundColor: '#A855F7', borderRadius: 3 },
  progressText: { fontSize: 12, color: '#6B7280', fontWeight: '500' },
  pointsNeeded: { fontSize: 12, color: '#F59E0B', marginBottom: 8, fontWeight: '500' },
  canClaimText: { fontSize: 12, color: '#10B981', marginBottom: 8, fontWeight: '600' },
  unlockedText: { fontSize: 12, color: '#10B981', marginBottom: 8, fontWeight: '600' },
  pickupDate: { fontSize: 20, fontWeight: 'bold', color: '#111827', marginTop: 12 },
  pickupTime: { fontSize: 14, color: '#6B7280', marginTop: 4 },
  pickupType: { fontSize: 12, color: '#10B981', marginTop: 8, fontWeight: '500' },
  scheduleActions: { marginTop: 12 },
  scheduleButton: { backgroundColor: '#5DADE2', borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
  scheduleButtonText: { color: 'white', fontSize: 14, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'flex-end' },
  modalScrollContent: { flexGrow: 1 },
  notificationModalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '80%',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    minHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalTitle: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
  notificationsList: {
    flex: 1,
  },
  notificationItem: {
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'flex-start',
  },
  notificationItemHigh: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FEE2E2',
  },
  notificationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  notificationContent: {
    flex: 1,
  },
  notificationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  notificationMessage: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 6,
  },
  notificationTime: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  notificationAction: {
    justifyContent: 'center',
    paddingLeft: 8,
  },
  notificationActionText: {
    fontSize: 24,
    color: '#9CA3AF',
    fontWeight: '300',
  },
  noNotifications: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  noNotificationsText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 16,
  },
  noNotificationsSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    marginTop: 8,
  },
  notificationDebug: {
    fontSize: 12,
    color: '#10B981',
    backgroundColor: '#ECFDF5',
    padding: 8,
    borderRadius: 6,
    marginBottom: 12,
    textAlign: 'center',
  },
  refreshButton: {
    marginTop: 16,
    backgroundColor: '#5DADE2',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  refreshButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  profileAvatarContainer: { alignItems: 'center', marginBottom: 32 },
  profileAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#DBEAFE',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 4,
    borderColor: '#5DADE2',
  },
  profileName: { fontSize: 24, fontWeight: 'bold', color: '#111827', marginBottom: 12 },
  userTypeBadge: {
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 16
  },
  userTypeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
    textTransform: 'capitalize'
  },
  profileInfo: { marginBottom: 32 },
  profileItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  profileLabel: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 6,
    marginLeft: 16,
    fontWeight: '500',
  },
  profileValue: {
    fontSize: 16,
    color: '#111827',
    fontWeight: '500',
    marginLeft: 16,
    flex: 1,
  },
  profileActions: { gap: 16, marginTop: 8 },
  editProfileButton: {
    backgroundColor: '#5DADE2',
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#5DADE2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  editProfileButtonText: { color: 'white', fontSize: 17, fontWeight: '600' },
  signOutButton: {
    backgroundColor: '#FEE2E2',
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#FEE2E2',
  },
  signOutButtonText: { color: '#EF4444', fontSize: 17, fontWeight: '600' },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 10,
    marginTop: 20
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    fontSize: 16,
    backgroundColor: '#F9FAFB',
    color: '#111827',
  },
  modalButtons: { flexDirection: 'row', gap: 16, marginTop: 32, marginBottom: 16 },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  modalCancelText: { fontSize: 17, color: '#6B7280', fontWeight: '600' },
  modalSaveButton: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: '#10B981',
    alignItems: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  modalSaveText: { fontSize: 17, color: 'white', fontWeight: '600' },
});